# Generated by Django 5.0 on 2024-01-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
