# Generated by Django 5.0 on 2024-01-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_created_at_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
